from __future__ import annotations

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., description="The user's input message.")
    thread_id: str = Field(..., description="Conversation thread identifier.")
    secured: bool = Field(
        default=True,
        description="True = `python run_agent.py --secured` graph. False = `python run_agent.py` (graph.py).",
    )


class ChatResponse(BaseModel):
    final_answer: str = Field(..., description="Final response generated by the agent.")
    status: str = Field(..., description="Execution status, e.g. success or error.")
